# Generated by Django 4.0.5 on 2022-07-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=350)),
                ('telephone', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField()),
                ('pImage', models.ImageField(upload_to='')),
            ],
        ),
    ]
