# Generated by Django 4.0.6 on 2022-08-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_telephone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_name']},
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(help_text='Enter Category', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(help_text='Enter date of event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(help_text='Enter Description', max_length=350),
        ),
        migrations.AlterField(
            model_name='event',
            name='pImage',
            field=models.ImageField(help_text='Enter Pimage', upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='telephone',
            field=models.CharField(help_text='Enter Telephone no.', max_length=50),
        ),
    ]
