# Generated by Django 4.0.6 on 2022-08-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='telephone',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='safe', max_length=400),
        ),
    ]
