# Generated by Django 4.0.6 on 2022-08-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('events', '0011_imagestore_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendes',
            field=models.ManyToManyField(blank=True, to='register.myclubusers'),
        ),
        migrations.AddField(
            model_name='event',
            name='manager',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
