# Generated by Django 4.0.6 on 2022-08-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_attendes_event_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestore',
            name='pImage',
            field=models.ImageField(help_text='Enter Pimage', upload_to='D:\\Web Development\\EventsNearMe\\NearEvent/static/media/uploaded'),
        ),
    ]
