# Generated by Django 4.1 on 2022-08-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestore',
            name='pImage',
            field=models.ImageField(help_text='Enter Pimage', upload_to='D:\\git\\NearEvents/static/media/uploaded'),
        ),
    ]
