# Generated by Django 4.0.6 on 2022-08-10 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_address_remove_event_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pImage', models.ImageField(help_text='Enter Pimage', upload_to='static/media/uploaded')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='pImage',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='events.imagestore'),
        ),
    ]
