# Generated by Django 4.0.6 on 2022-08-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_pimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagestore',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
